name: Build APK

on:
  push:
    branches: [ "principal", "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Se houver o ZIP na raiz, descompacta e traz o projeto v6
      - name: Unzip project if zip exists
        run: |
          if [ -f SemaforoRideshareApp_v6.zip ]; then
            echo "ZIP encontrado. Descompactando..."
            unzip -o SemaforoRideshareApp_v6.zip
            # O ZIP contém a pasta SemaforoRideshareApp com tudo dentro
            rsync -a SemaforoRideshareApp/ .
            rm -rf SemaforoRideshareApp
            # Apaga arquivos com nomes em PT que atrapalham
            rm -f construir.gradle configurações.gradle configuracoes.gradle construir.yml
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "Apply v6 payload from zip" || true
          else
            echo "Nenhum ZIP encontrado, seguindo com o conteúdo atual."
          fi

      # 2) Checagens mínimas
      - name: Check project layout
        run: |
          test -f settings.gradle || (echo "ERRO: settings.gradle não encontrado"; exit 1)
          test -f build.gradle    || (echo "ERRO: build.gradle não encontrado"; exit 1)
          test -d app             || (echo "ERRO: pasta app/ não encontrada"; exit 1)
          ls -la

      # 3) JDK + SDK Android
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 4) Instala Gradle (se o projeto não tiver gradlew)
      - name: Install Gradle (no wrapper)
        run: |
          if [ ! -f gradlew ]; then
            curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
            unzip -q gradle.zip
            echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH
            echo "USING gradle command"
            echo "gradle assembleDebug" > run_build.sh
            chmod +x run_build.sh
          else
            echo "USING ./gradlew"
            echo "./gradlew assembleDebug" > run_build.sh
            chmod +x run_build.sh
          fi

      # 5) Compila
      - name: Build APK
        run: bash run_build.sh

      # 6) Publica o APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
