 git push
name: Unzip Project

on:
  push:
    paths:
      - 'SemaforoRideshareApp_v6.zip'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar ZIP
        run: |
          if [ ! -f SemaforoRideshareApp_v6.zip ]; then
            echo "ZIP não encontrado na raiz do repositório."
            exit 1
          fi

      - name: Descompactar payload
        run: |
          set -e
          unzip -o SemaforoRideshareApp_v6.zip
          # O ZIP contém uma pasta "SemaforoRideshareApp" com tudo dentro:
          rsync -a --delete SemaforoRideshareApp/ .
          rm -rf SemaforoRideshareApp

          # Remover arquivos com nomes em PT que atrapalham
          rm -f construir.gradle configuracoes.gradle configurações.gradle construir.yml

          # Garantir que a pasta workflows existe
          mkdir -p .github/workflows

      - name: Garantir build.yml
        run: |
          cat > .github/workflows/build.yml <<'YAML'
          name: Build APK
          on:
            push:
              branches: [ "principal", "main", "master" ]
            workflow_dispatch:
          jobs:
            build:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout code
                  uses: actions/checkout@v4
                - name: Set up JDK 17
                  uses: actions/setup-java@v4
                  with:
                    distribution: 'temurin'
                    java-version: '17'
                - name: Install Android SDK
                  uses: android-actions/setup-android@v3
                - name: Install Gradle (no wrapper)
                  run: |
                    curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
                    unzip -q gradle.zip
                    echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH
                - name: Build with Gradle
                  run: gradle assembleDebug
                - name: Upload APK
                  uses: actions/upload-artifact@v4
                  with:
                    name: app-debug
                    path: app/build/outputs/apk/debug/app-debug.apk
          YAML

      - name: Commit e push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Unzip v6 + garantir build.yml" || echo "Nada para commitar"
          git push
