name: Unzip Project

on:
  push:
    paths:
      - 'SemaforoRideshareApp_v6.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # permite fazer commit no repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip payload
        run: |
          rm -rf SemaforoRideshareApp app build.gradle settings.gradle README.md .github/workflows/build.yml || true
          unzip -o SemaforoRideshareApp_v6.zip
          # o ZIP contém uma pasta "SemaforoRideshareApp" com tudo dentro
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Unzip v6 payload" || echo "Nada para commitar"

      - name: Ensure build workflow present
        run: |
          mkdir -p .github/workflows
          cat > .github/workflows/build.yml <<'YAML'
          name: Build APK
          on:
            push:
              branches: [ "principal", "main", "master" ]
            workflow_dispatch:
          jobs:
            build:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout code
                  uses: actions/checkout@v4
                - name: Set up JDK 17
                  uses: actions/setup-java@v4
                  with:
                    distribution: 'temurin'
                    java-version: '17'
                - name: Install Android SDK
                  uses: android-actions/setup-android@v3
                - name: Install Gradle (no wrapper)
                  run: |
                    curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
                    unzip -q gradle.zip
                    echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH
                - name: Build with Gradle
                  run: gradle assembleDebug
                - name: Upload APK
                  uses: actions/upload-artifact@v4
                  with:
                    name: app-debug
                    path: app/build/outputs/apk/debug/app-debug.apk
          YAML
          git add .github/workflows/build.yml
          git commit -m "Ensure build workflow" || echo "Build workflow already there"

      - name: Push changes
        run: |
          git push
